apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: root-argocd
    namespace: argocd
spec:
    project: default
    source:
        repoURL: 'https://github.com/MohamedElSayed215/daf-devops-task.git'
        path: app
        targetRevision: main
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
