{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secret",
    "namespace": "shop",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secret",
        "namespace": "shop",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "POSTGRES_DB": "AgCL1MeCsBtDkFCbIVWGCpncburtEhan7cTlMr05fSb+Po2BC6hgj16atztnc1szETEfQF+0M1NJnBBehJxHV9/aipCMipBB2C1Az+W31Xp9Vj84Qej3MJSH+RZg+6bSm2vl5WGgiZITety8dZp3SI1XcXugGQ3+4ikU3DbwMSkS0zRtw1fMBY4KLoIlQ0YsN/4pVfuhgMeCd6vve0whOxtnUJPhqr6iXVKSvDTnR8iucUaMBZI3lSWf/cxzLIjUA+U7Kfi2oWszjSMqUb9OWVNiy36iUrQCnfoRMJ05FA8A5VDLCnk9kAdr+hY8/RFg/9RRBbLNOqvVD7GIJPBJSli2x53jH9MjWPhgJ0w6Qk8EGxWOEA1El8KHpZq/Z4xObnkIPKbM52hZ0Whd5df+Y2NMqzrsE7RSfNzNWr6ShSv2f5e4V2f9ptl/63K1Zn+h5x6F+4tel/6MpjNQLhFI1bk4Gtki0WiP233tOz48NNcGUgglJE8AWjDGsffXLliKA784wB7AfjKWh1zoLTgMPdgB4vGa9JkjyRYtfhyUQ6oQJEYRbJ3hnGl2z7lwWWKu63txqcNt586fIFnZ35ZytlxE38EIgFx3nS8VazRFmypJT0V5gA29zj0BtMqeoDKyzNuGFXMVTORNbzpmKGisuQTfae9UTZkCq8NyrjTSmD2k+c6zLkvBgI5MJ3B5S88Fd92xd576",
      "POSTGRES_PASSWORD": "AgA8zbCMkk6+MjT88PXDMQyguad05B95Lt0az1lbj12WWhs2rxeepvzFw2OtGoyhHYBX2CsIBd9T0dHkckhw+tjMcDNskGZ9tcF7qyboMe32fSixzHF2Al6RpBW2mfzHgAPEL+5u66Y+zCQGnocwZuxG+3ZcIqlrqTKfw7Y0IGnxqCVJYoWdB/q0YdiSQCjCigtweu4wTY60JanSLDajHG74KmXnLZXGrRMrIinDZjeYbFOuQPKKO1uCfgSSuv4F6JkcmFujqFk7yr9zTbN3fS4NtUc4MRIrwRqe7U+plgd4U2rq97uFaJdmA7lIa8eWzEvUpdwIIAsFysJPoMuncXmMR0p9aWNvFBiy+DrJfYFZeGRsRhO33+oTOG9KPcrkYegXg83WcE/kVqRzy8jXlGqS5G1fGlRNFv6QHF5tUxSmPUrbHlvMgERstkVj6U1jBtB0b7Awv0kPqCCqYwnI9JoGAm4iqkrjujuPgx1AOKHdY1O5HBhZg+uljOrQcDuULfWYIhrqXIZsCfUpufWCia6Jwdmypn4iaCgWBtGTWtMgq4kO2GEE+cCFkysaXUxbDfNOYj7SAFcDz5/H+DvVwNLC6SZeW87U60bJ+K7sWk8F7pSzY1sh80fpCjVP2pmhri5v4pcLVYBBFQVKfXn8rO4TzpRMYMiZyt3CFj+NY7RHgLBvjd//WrlExHF4UL9UhuoVlxtfmyoyoQxrPDkO",
      "POSTGRES_USER": "AgA58uWGkVhntr89iHyDvd/kozy3Tbx46hglCzM2YRctu2JL65A+WlV9HVcULHlW46BKy6Qm4CNWLSrLm/V2Ph4JKi2vdFua00L1/LxsHS3mHvxOULkkkF/XJ2SHmE0CJ/df6/VOLOYJU0SJcxl/TjSUoivglhIrN+dyZgB4xRL2dyAenTQwD6yyjpBOQ+4CXwk6dwuNCdomVLc7xJRwQQmy2mb54HJqCOzqps4IIt2VjBym0txaH+dx9r1rtKrekmmgVnh3b8WQ3BgzNowfqzHpKcufAKJg3SYrfXkRQrsWcqMJD4MObTMyBxHzjLfNl4v/K8tnQOG2+i+rtbLIGCHsxhcxYNnhFab/f2CFrWDwyQWcLgMX4bG3eHDAj8O3r1q8vriavhHoa1uFQS+Fmb3FbJuWjsRuNSVRioxLtrRFtASukYoLUZTCVpuo6xKStjCFBzhZhBt1afdky0zEnR1TlxDmN5aJ/4zPg8kJ19bE+Vns6uk5HgWpFf226ZOA5goMqD/N4HfbEfflyAoACH//0iDiRsDxd0pBFO/bXrRMYEyAiZjlxu3M1VUwxxZlbS6Mx8bArIZClI0nDMzUwipSho8PKlpQkmZIz0RPwsIntfCF+nZgvU7FrDTg4D9eGoD6am4qkI3dp2lXsKN+HOspeo6ubkurzqQ4Yc9O8YX3b17lJisu97S5lE+CIGAgNemXFUSe"
    }
  }
}
